export const PERSONAL_ROLES: string[] = [
  'Desarrollador Web Junior',
  'Desarrollador Frontend Junior Angular',
  'Desarrollador Frontend Junior React',
  'Desarrollador Backend Junior Python',
  'Desarrollador Backend Junior PHP',
  'Desarrollador Full Stack Junior',
  'Programador Junior',
  'Software Developer Junior',
  'Ingeniero de Software Junior',
  'Analista de Datos Junior',
  'Data Analyst Junior',
  'Business Intelligence Junior',
  'Analista BI Junior',
  'Analista de Información Junior',
  'Data Assistant',
  'Analista SQL Junior',
  'Desarrollador de Automatización',
  'RPA Developer Junior',
  'Analista de Procesos TI',
  'Especialista en Automatización',
  'Desarrollador de Bots',
  'Desarrollador IA Junior',
  'Analista de Transformación Digital',
  'Soporte TI',
  'Mesa de Ayuda',
  'Help Desk Junior',
  'Soporte Técnico Nivel 1',
  'Soporte Técnico Nivel 2',
  'Técnico en Redes',
  'Analista de Soporte TI',
  'Administrador de Sistemas Junior',
  'Cloud Engineer Junior',
  'DevOps Junior',
  'Ingeniero Cloud AWS Junior',
  'Administrador Cloud Junior',
  'Site Reliability Engineer Junior'
];

